# Generated by Django 4.2.9 on 2026-03-22 03:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('goal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('category', models.CharField(choices=[('one_time', 'One-Time Donor'), ('recurring', 'Recurring Donor'), ('major', 'Major Donor'), ('member', 'Sustaining Member')], default='one_time', max_length=20)),
                ('total_donations', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount donated', max_digits=12)),
                ('number_of_donations', models.IntegerField(default=0)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('opt_in_email', models.BooleanField(default=True)),
                ('opt_in_newsletter', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonorAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('restore', 'Restored')], max_length=20)),
                ('changed_by', models.CharField(default='admin', max_length=255)),
                ('changed_fields', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='donors.donor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['email'], name='donors_dono_email_17ddb3_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['category'], name='donors_dono_categor_cc65e6_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['created_at'], name='donors_dono_created_d12ba8_idx'),
        ),
    ]
