# Generated by Django 4.2.9 on 2026-03-22 03:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReceiptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField(help_text='Use {{donor_name}}, {{amount}}, {{tax_year}}, {{organization_name}} as placeholders')),
                ('sender_name', models.CharField(default='KPALS', max_length=255)),
                ('sender_email', models.EmailField(max_length=254)),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxReceiptEmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_year', models.IntegerField()),
                ('total_recipients', models.IntegerField()),
                ('successfully_sent', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('sent_by', models.CharField(default='admin', max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tax_receipts.taxreceipttemplate')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_year', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('receipt_html', models.TextField(blank=True, null=True)),
                ('receipt_pdf_url', models.URLField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('email_error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donations_included', models.ManyToManyField(blank=True, to='donations.donation')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_receipts', to='donors.donor')),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tax_receipts.taxreceipttemplate')),
            ],
            options={
                'ordering': ['-tax_year', '-created_at'],
                'indexes': [models.Index(fields=['donor', 'tax_year'], name='tax_receipt_donor_i_5fae53_idx'), models.Index(fields=['email_delivery_status'], name='tax_receipt_email_d_1f8f51_idx')],
                'unique_together': {('donor', 'tax_year')},
            },
        ),
    ]
