# Generated by Django 4.2.9 on 2026-03-22 03:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('total_records', models.IntegerField()),
                ('successful_imports', models.IntegerField()),
                ('failed_imports', models.IntegerField()),
                ('error_details', models.JSONField(default=dict)),
                ('imported_by', models.CharField(default='admin', max_length=255)),
            ],
            options={
                'ordering': ['-import_date'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('donation_date', models.DateField()),
                ('donation_type', models.CharField(choices=[('one_time', 'One-Time'), ('recurring', 'Recurring')], default='one_time', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20, null=True)),
                ('next_expected_donation', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('check', 'Check'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('other', 'Other')], default='check', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tax_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donors.campaign')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donors.donor')),
            ],
            options={
                'ordering': ['-donation_date'],
                'indexes': [models.Index(fields=['donor', 'donation_date'], name='donations_d_donor_i_c7b8c4_idx'), models.Index(fields=['tax_year'], name='donations_d_tax_yea_b2fbc6_idx'), models.Index(fields=['created_at'], name='donations_d_created_26bd74_idx')],
            },
        ),
    ]
